
import java.awt.Desktop;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import java.net.URI;

public class EasyGame extends javax.swing.JFrame {

    private int numToGuess = 34;
    private int attempts = 3;
    private int timeRemaining = 45;
    private int score = 0;
    private Timer timer;
            
    public EasyGame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        TimeLabel = new javax.swing.JLabel();
        EasyGameAttempts = new javax.swing.JLabel();
        EasyGameGuessBtn = new javax.swing.JButton();
        EasyGameReplayBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        NumberTextField = new javax.swing.JTextField();
        ResultLabel = new javax.swing.JLabel();
        VideoAd = new javax.swing.JButton();
        scoreLabel = new javax.swing.JLabel();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        TimeLabel.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        TimeLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0), 2));

        EasyGameAttempts.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N

        EasyGameGuessBtn.setBackground(new java.awt.Color(255, 153, 0));
        EasyGameGuessBtn.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        EasyGameGuessBtn.setText("GUESS");
        EasyGameGuessBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EasyGameGuessBtnActionPerformed(evt);
            }
        });

        EasyGameReplayBtn.setBackground(new java.awt.Color(255, 153, 0));
        EasyGameReplayBtn.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        EasyGameReplayBtn.setText("TRY AGAIN");
        EasyGameReplayBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EasyGameReplayBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel1.setText("NUMBER:");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0), 2));

        NumberTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        NumberTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0), 2));
        NumberTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumberTextFieldActionPerformed(evt);
            }
        });

        ResultLabel.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N

        VideoAd.setBackground(new java.awt.Color(255, 153, 0));
        VideoAd.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        VideoAd.setText("Watch AD");
        VideoAd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VideoAdActionPerformed(evt);
            }
        });

        scoreLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(scoreLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(EasyGameAttempts, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 135, Short.MAX_VALUE)
                        .addComponent(TimeLabel)
                        .addGap(146, 146, 146))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(NumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(105, 105, 105)
                        .addComponent(EasyGameGuessBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(VideoAd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(EasyGameReplayBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(95, 95, 95))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(ResultLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EasyGameAttempts, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TimeLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(scoreLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(NumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(EasyGameGuessBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(ResultLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(EasyGameReplayBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VideoAd))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 53, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NumberTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumberTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumberTextFieldActionPerformed

    private void EasyGameGuessBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EasyGameGuessBtnActionPerformed
        // TODO add your handling code here:
        
        int guess = Integer.parseInt(NumberTextField.getText());
        
         String input = NumberTextField.getText().trim();
      if(input.isEmpty()){
          JOptionPane.showMessageDialog(null, "Please enter a number!");
          return;
      }
      
      try{
          int number = Integer.parseInt(input);
          if(number<1|| number>50){
              JOptionPane.showMessageDialog(null,"Number must be between 1 and 50!" );
              return;
          }
          System.out.println("Valid input:" + number);
      }catch(NumberFormatException ex){
          JOptionPane.showMessageDialog(this, "Invalid input, Please enter a number");
      }
        
        
        if(guess<numToGuess){
            ResultLabel.setText("Too Low!");
            
            scoreLabel.setText("Score: " + score);
        }
        else if(guess>numToGuess){
            ResultLabel.setText("Too High!");
            
            scoreLabel.setText("Score: " + score);
        }
       
        else{
            ResultLabel.setText("Congratulations! You guessed it Right!");
            score += 10;
            scoreLabel.setText("Score: "+ score);
            timer.stop();
            EasyGameReplayBtn.setEnabled(false);
            VideoAd.setEnabled(false);
            
            
    }//GEN-LAST:event_EasyGameGuessBtnActionPerformed
 attempts--;
   EasyGameAttempts.setText("Attempts Remaining: "+ attempts);
   
   if(attempts == 0 && score == 0){
       JOptionPane.showMessageDialog(null, "Game Over!, Watch Ad for 3 more attempts!");
       timer.stop();
       
   }
   
   timeRemaining--;
   TimeLabel.setText("Time Remaining: " + timeRemaining + "seconds");
   
   if(timeRemaining == 0){
       JOptionPane.showMessageDialog(null, "Time's Up!. Game Over!");
       System.exit(0);
   }
    }


    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        
        timer = new Timer(1000, new ActionListener(){
            @Override 
            public void actionPerformed(ActionEvent e){
                timeRemaining--;
                TimeLabel.setText("Time Remaining: "+ timeRemaining + "seconds");
                
                if(timeRemaining == 0){
                    JOptionPane.showMessageDialog(null, "Times Up! Game Over!");
                    System.exit(0);
                }
            }
        });
        timer.start();
    }//GEN-LAST:event_formWindowOpened

    private void EasyGameReplayBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EasyGameReplayBtnActionPerformed
        // TODO add your handling code here:
        
        if(attempts>0){
            NumberTextField.setEnabled(true);
            EasyGameGuessBtn.setEnabled(true);
            ResultLabel.setText("");
            NumberTextField.setText("");
        }
        else{
            JOptionPane.showMessageDialog(null, "No attempts remaining! Game Over!");
        }
    }//GEN-LAST:event_EasyGameReplayBtnActionPerformed

    private void VideoAdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VideoAdActionPerformed
        // TODO add your handling code here:
        Desktop desktop = Desktop.isDesktopSupported()?
                Desktop.getDesktop() : null;
        if(desktop != null && desktop.isSupported(Desktop.Action.BROWSE)){
        try{
            URI uri = new URI("");
            desktop.browse(uri);
            attempts += 3;
            
            EasyGameAttempts.setText("Attempts Remaining: "+ attempts);
            EasyGameGuessBtn.setEnabled(true);
            ResultLabel.setText("");
            
        }catch(Exception e ){
            JOptionPane.showMessageDialog(null,"Error opening Video");
        }
        
    }
 
                
    }//GEN-LAST:event_VideoAdActionPerformed
  
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EasyGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EasyGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EasyGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EasyGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EasyGame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel EasyGameAttempts;
    private javax.swing.JButton EasyGameGuessBtn;
    private javax.swing.JButton EasyGameReplayBtn;
    private javax.swing.JTextField NumberTextField;
    private javax.swing.JLabel ResultLabel;
    private javax.swing.JLabel TimeLabel;
    private javax.swing.JButton VideoAd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel scoreLabel;
    // End of variables declaration//GEN-END:variables
}
