import java.awt.Desktop;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import java.net.URI;

public class MeduimGame extends javax.swing.JFrame {

    private int numToGuess = 83;
    private int attempts = 2;
    private int timeRemaining = 30;
    private int score = 0;
    private Timer timer;
    
    public MeduimGame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TimeLabel = new javax.swing.JLabel();
        EasyGameAttempts = new javax.swing.JLabel();
        MeduimGameGuessBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        NumberTextField = new javax.swing.JTextField();
        ResultLabel = new javax.swing.JLabel();
        MeduimGameReplayBtn = new javax.swing.JButton();
        scoreLabel = new javax.swing.JLabel();
        VideoAd = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        TimeLabel.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        TimeLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0), 2));

        EasyGameAttempts.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N

        MeduimGameGuessBtn.setBackground(new java.awt.Color(255, 153, 0));
        MeduimGameGuessBtn.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        MeduimGameGuessBtn.setText("GUESS");
        MeduimGameGuessBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MeduimGameGuessBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel1.setText("NUMBER:");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0), 2));

        NumberTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0)));
        NumberTextField.setPreferredSize(new java.awt.Dimension(521, 368));
        NumberTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumberTextFieldActionPerformed(evt);
            }
        });

        ResultLabel.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N

        MeduimGameReplayBtn.setBackground(new java.awt.Color(255, 153, 0));
        MeduimGameReplayBtn.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        MeduimGameReplayBtn.setText("TRY AGAIN");
        MeduimGameReplayBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MeduimGameReplayBtnActionPerformed(evt);
            }
        });

        scoreLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        VideoAd.setBackground(new java.awt.Color(255, 153, 0));
        VideoAd.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        VideoAd.setText("WATCH AD");
        VideoAd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VideoAdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(VideoAd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(MeduimGameReplayBtn)
                .addGap(48, 48, 48))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(EasyGameAttempts, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(TimeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(scoreLabel)))
                .addContainerGap(15, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(NumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(MeduimGameGuessBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(ResultLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(28, 28, 28))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TimeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(EasyGameAttempts, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(scoreLabel)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MeduimGameGuessBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(37, 37, 37)
                .addComponent(ResultLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(MeduimGameReplayBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(VideoAd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NumberTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumberTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumberTextFieldActionPerformed

    private void MeduimGameGuessBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MeduimGameGuessBtnActionPerformed

        int guess = Integer.parseInt(NumberTextField.getText());

         String input = NumberTextField.getText().trim();
      if(input.isEmpty()){
          JOptionPane.showMessageDialog(null, "Please enter a number!");
          return;
      }
      
      try{
          int number = Integer.parseInt(input);
          if(number<1|| number>100){
              JOptionPane.showMessageDialog(null,"Number must be between 1 and 100!" );
              return;
          }
          System.out.println("Valid input:" + number);
      }catch(NumberFormatException ex){
          JOptionPane.showMessageDialog(this, "Invalid input, Please enter a number");
      }
        
        if(guess<numToGuess){
            ResultLabel.setText("Too Low!");
            scoreLabel.setText("Score: " + score);
        }
        else if(guess>numToGuess){
            ResultLabel.setText("Too High!");
            scoreLabel.setText("Score: " + score);
        }

        else{
            ResultLabel.setText("Congratulations! You guessed it Right!");
              score += 10;
            scoreLabel.setText("Score: "+ score);
            timer.stop();
            MeduimGameReplayBtn.setEnabled(false);
            VideoAd.setEnabled(false);

          
    }//GEN-LAST:event_MeduimGameGuessBtnActionPerformed

      attempts--;
   EasyGameAttempts.setText("Attempts Remaining: "+ attempts);
   
   if(attempts == 0){
       JOptionPane.showMessageDialog(null, "Game Over!, Watch Ad for 3 more attempts!");
       System.exit(0);
   }
   
   timeRemaining--;
   TimeLabel.setText("Time Remaining: " + timeRemaining + "seconds");
   
   if(timeRemaining == 0){
       JOptionPane.showMessageDialog(null, "Time's Up!. Game Over!");
       System.exit(0);
   }  
    }    
        
    private void MeduimGameReplayBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MeduimGameReplayBtnActionPerformed
        // TODO add your handling code here:

           if(attempts>0){
            NumberTextField.setEnabled(true);
            MeduimGameGuessBtn.setEnabled(true);
            ResultLabel.setText("");
            NumberTextField.setText("");
        }
        else{
            JOptionPane.showMessageDialog(null, "No attempts remaining! Game Over!");
        }
        
    }//GEN-LAST:event_MeduimGameReplayBtnActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        
        timer = new Timer(1000, new ActionListener(){
            @Override 
            public void actionPerformed(ActionEvent e){
                timeRemaining--;
                TimeLabel.setText("Time Remaining: "+ timeRemaining + "seconds");
                
                if(timeRemaining == 0){
                    JOptionPane.showMessageDialog(null, "Times Up! Game Over!");
                    System.exit(0);
                }
            }
        });
        timer.start();
    }//GEN-LAST:event_formWindowOpened

    private void VideoAdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VideoAdActionPerformed
        // TODO add your handling code here:
        
        
           Desktop desktop = Desktop.isDesktopSupported()?
                Desktop.getDesktop() : null;
        if(desktop != null && desktop.isSupported(Desktop.Action.APP_OPEN_FILE)){
        try{
            URI uri = new URI("C:\\Users\\Admin\\Videos");
            desktop.browse(uri);
            attempts += 3;
            
            EasyGameAttempts.setText("Attempts Remaining: "+ attempts);
            MeduimGameGuessBtn.setEnabled(true);
            ResultLabel.setText("");
            
        }catch(Exception e ){
            JOptionPane.showMessageDialog(null,"Error opening Video");
        }
        }
    }//GEN-LAST:event_VideoAdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MeduimGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MeduimGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MeduimGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MeduimGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MeduimGame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel EasyGameAttempts;
    private javax.swing.JButton MeduimGameGuessBtn;
    private javax.swing.JButton MeduimGameReplayBtn;
    private javax.swing.JTextField NumberTextField;
    private javax.swing.JLabel ResultLabel;
    private javax.swing.JLabel TimeLabel;
    private javax.swing.JButton VideoAd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel scoreLabel;
    // End of variables declaration//GEN-END:variables
}
